site_name: Obsidian Kanban
repo_url: https://github.com/mgmeyers/obsidian-kanban
edit_uri: edit/main/docs/docs/
theme:
  name: material
  palette:
    primary: blue
nav:
  - Overview: 'index.md'
  - How tos: 'How to/index.md'
  - Settings: 'Settings/index.md'
plugins:
  - search
